package com.devtale.financeBackend.mapper;

import com.devtale.financeBackend.dto.TransactionDto;
import com.devtale.financeBackend.model.Transaction;
import org.springframework.stereotype.Component;

@Component
public class TransactionMapper {


    public TransactionDto toDto(Transaction transaction){
        if(transaction == null){
            return null;
        }
        TransactionDto dto = new TransactionDto();
        dto.setId(transaction.getId());
        dto.setDescription(transaction.getDescription());
        dto.setAmount(transaction.getAmount());
        dto.setDate(transaction.getDate());
        dto.setCategory(transaction.getCategory());
        dto.setType(transaction.getType());
        return dto;
    }


    public  Transaction toEntity(TransactionDto dto){
        if(dto == null){
            return null;
        }
        // We do not set the ID here, because it's generated by the database.
        // We also do not set the User here. The service layer will handle that.
        Transaction transaction = new Transaction();
        transaction.setDescription(dto.getDescription());
        transaction.setAmount(dto.getAmount());
        transaction.setDate(dto.getDate());
        transaction.setCategory(dto.getCategory());
        transaction.setType(dto.getType());
        return transaction;
    }

}
